#
#	Ivy, C interface
#
#	Copyright (C) 1997-2002
#	Centre d'Études de la Navigation Aérienne
#
#	Makefile.win32
#
#	Authors: François-Régis Colin <fcolin@cena.fr>
#		 Stéphane Chatty <chatty@cena.fr>
#		 Yannick Jestin <jestin@cena.fr>
#
#	Please refer to file version.h for the
#	copyright notice regarding this software
#

# change this in version.h too !!!!
MAJOR=3
MINOR=17

!IFNDEF PLATFORM
PLATFORM=x64
!ENDIF

!IFNDEF CONFIGURATION
CONFIGURATION=Release
!ENDIF

!IFNDEF PCRE2_INC
PCRE2_INC=/I"..\..\pcre2\include"
!ENDIF

!IFNDEF PCRE2_LIB
PCRE2_LIB="..\..\pcre2\build\$(PLATFORM)\$(CONFIGURATION)\pcre2-8.lib"
!ENDIF

CASESENSITIVE = yes
!IF "$(CASESENSITIVE)" == "no"
PCRE_OPT = PCRE2_CASELESS
REGCOMP_OPT = REG_ICASE
!ELSE
PCRE_OPT = 0
REGCOMP_OPT = REG_EXTENDED
!ENDIF

CC=cl
CXX=cl
AR=lib
CFLAGS=/nologo /W4 /O2 /MD /DWIN32 /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS
LDFLAGS=/nologo
LIBTOOL=$(AR) /nologo
TOOLS_DIR=..\tools

REGEXP=/DUSE_PCRE_REGEX /DPCRE_OPT=$(PCRE_OPT)

OBJ=intervalRegexp.obj ivyloop.obj timer.obj ivysocket.obj ivy.obj param.obj ivybuffer.obj ivyfifo.obj ivybind.obj
TARGETLIBS=ivy.dll

.c.obj:
	$(CC) $(CFLAGS) /c $*.c

.cpp.obj:
	$(CXX) $(CFLAGS) /c $*.cpp

all: static-libs shared-libs tools

static-libs: libivy.lib

shared-libs: $(TARGETLIBS)

ivybind.obj: ivybind.c
	$(CC) $(CFLAGS) $(REGEXP) $(PCRE2_INC) /c ivybind.c

libivy.lib: $(OBJ)
	-del /f $@
	$(LIBTOOL) /out:$@ $(OBJ)

ivy.dll: $(OBJ)
	link $(LDFLAGS) /dll /out:$@ /DEF:libIvy.def $(OBJ) $(PCRE2_LIB) ws2_32.lib

tools: static-libs
	@(cd $(TOOLS_DIR) && $(MAKE) -f Makefile.win32)

clean:
	-del /f $(TARGETLIBS) *.obj *.lib *.dll *~
	@(cd $(TOOLS_DIR) && $(MAKE) -f Makefile.win32 clean)
