#
#       Ivy, C interface
#
#       Copyright (C) 1997-2014
#       Centre d'Études de la Navigation Aérienne
#
#       Makefile.osx
#
#       Authors: François-Régis Colin <fcolin@cena.fr>
#                Stéphane Chatty <chatty@cena.fr>
#                Yannick Jestin <jestin@cena.fr>
#                Piotr Esden-Tempski <piotr@esden.net>
#
#       Please refer to file version.h for the
#       copyright notice regarding this software
#

# change this in version.h too !!!!
MAJOR=3
MINOR=16

LIB=/lib

# by default use fPIC on all systems
FPIC ?= -fPIC

ARCH := $(shell uname -m)

ifeq ($(ARCH),arm64)
	HOMEBREW_PREFIX ?= /opt/homebrew
else
	HOMEBREW_PREFIX ?= /usr/local
endif

ifndef PREFIX
	PREFIX=$(HOMEBREW_PREFIX)
endif

PCRE2_CONFIG ?= $(shell command -v pcre2-config 2>/dev/null)
ifeq ($(PCRE2_CONFIG),)
	PCRE2_CONFIG := $(HOMEBREW_PREFIX)/opt/pcre2/bin/pcre2-config
endif

ifeq ($(wildcard $(PCRE2_CONFIG)),)
	PCREINC = $(shell pkg-config --cflags libpcre2-8 2>/dev/null)
	PCRELIB = $(shell pkg-config --libs libpcre2-8 2>/dev/null)
else
	PCREINC = $(shell $(PCRE2_CONFIG) --cflags)
	PCRELIB = $(shell $(PCRE2_CONFIG) --libs8)
endif

CASESENSITIVE = "yes"
ifeq ($(CASESENSITIVE), "no")
	PCRE_OPT=PCRE2_CASELESS
	REGCOMP_OPT=REG_ICASE
else
	PCRE_OPT=0
	REGCOMP_OPT=REG_EXTENDED
endif
REGEXP= -DUSE_PCRE_REGEX -DPCRE_OPT=$(PCRE_OPT)

ifeq ($(ARCH),x86_64)
	DARWIN_ARCH_CFLAGS ?= -march=x86-64-v3 -mtune=generic
else
	DARWIN_ARCH_CFLAGS ?=
endif

XCRUN_CLANG := $(shell xcrun --find clang 2>/dev/null)
XCRUN_CLANGXX := $(shell xcrun --find clang++ 2>/dev/null)
SDKROOT := $(shell xcrun --sdk macosx --show-sdk-path 2>/dev/null)
SYSROOT_FLAGS := $(if $(SDKROOT),-isysroot $(SDKROOT),)
CC := $(if $(XCRUN_CLANG),$(XCRUN_CLANG),clang)
CXX := $(if $(XCRUN_CLANGXX),$(XCRUN_CLANGXX),clang++)
OMPCC ?= $(CC)
OMPCXX ?= $(CXX)
AR ?= ar
LIBTOOL ?= $(AR) q

LIBOMP_PREFIX ?= $(HOMEBREW_PREFIX)/opt/libomp
ifneq ($(wildcard $(LIBOMP_PREFIX)/include),)
	OPENMP_CPPFLAGS ?= -I$(LIBOMP_PREFIX)/include
	OPENMP_LDFLAGS ?= -L$(LIBOMP_PREFIX)/lib -Wl,-rpath,$(LIBOMP_PREFIX)/lib
else
	OPENMP_CPPFLAGS ?=
	OPENMP_LDFLAGS ?=
endif

LDFLAGS += $(SYSROOT_FLAGS)

CFLAGS ?= -g -Wall -Wshadow $(FPIC) $(DARWIN_ARCH_CFLAGS) $(SYSROOT_FLAGS)
CXXFLAGS ?= $(CFLAGS)
OMPCFLAGS = $(CFLAGS) $(OPENMP_CPPFLAGS) -Xpreprocessor -fopenmp -DOPENMP=1 -D_REENTRANT
OMPCXXFLAGS = $(CXXFLAGS) $(OPENMP_CPPFLAGS) -Xpreprocessor -fopenmp -DOPENMP=1 -D_REENTRANT
OMPLIB = $(OPENMP_LDFLAGS) -lomp

GLIBINC = `pkg-config --cflags glib-2.0`
GLIBLIB = `pkg-config --libs glib-2.0`

OBJ = ivyloop.o timer.o ivysocket.o ivy.o ivybuffer.o ivyfifo.o ivybind.o intervalRegexp.o param.o
OMPOBJ = ivyloop.o timer.o ivysocket_omp.o ivy_omp.o ivybuffer.o ivyfifo.o ivybind.o intervalRegexp.o param.o
GLIBOBJ = ivyglibloop.o ivysocket.o ivy.o ivybuffer.o ivyfifo.o ivybind.o intervalRegexp.o param.o

TOOLS_DIR = ../tools

.c.o:
	$(CC) $(CFLAGS) -c $*.c

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $*.cpp

all: static-libs shared-libs pkgconf tools
libomp: libivy_omp.a

omp: libomp
	@(cd $(TOOLS_DIR) && $(MAKE) -f Makefile.osx omp)

static-libs: libivy.a

shared-libs: libivy.dylib

ivybind.o: ivybind.c
	$(CC) -c $(CFLAGS) $(REGEXP) $(PCREINC) ivybind.c

ivy_omp.o: ivy.c
	$(OMPCC) -c $(OMPCFLAGS) -o ivy_omp.o ivy.c

ivysocket_omp.o: ivysocket.c
	$(OMPCC) -c $(OMPCFLAGS) -o ivysocket_omp.o ivysocket.c

ivyglibloop.o: ivyglibloop.c ivyglibloop.h
	$(CC) -c $(CFLAGS) $(GLIBINC) ivyglibloop.c

libivy.a: $(OBJ)
	rm -f $@
	$(LIBTOOL) $@ $(OBJ)

libivy_omp.a: $(OMPOBJ)
	rm -f $@
	$(LIBTOOL) $@ $(OMPOBJ)

libivy.dylib: $(OBJ)
	$(CC) $(LDFLAGS) -dynamiclib -install_name $(PREFIX)/lib/libivy.dylib -o $@ $(OBJ) $(PCRELIB)

libivy_omp.dylib: $(OMPOBJ)
	$(OMPCC) $(LDFLAGS) -dynamiclib -install_name $(PREFIX)/lib/libivy_omp.dylib -o $@ $(OMPOBJ) $(PCRELIB) $(OMPLIB)

libglibivy.a: $(GLIBOBJ)
	rm -f $@
	$(LIBTOOL) $@ $(GLIBOBJ)

libglibivy.dylib: $(GLIBOBJ)
	$(CC) $(LDFLAGS) -dynamiclib -install_name $(PREFIX)/lib/libglibivy.dylib -o $@ $(GLIBOBJ) $(PCRELIB) $(GLIBLIB)

installlibs: static-libs shared-libs
	test -d $(DESTDIR)$(PREFIX)$(LIB) || mkdir -p $(DESTDIR)$(PREFIX)$(LIB)
	install -m644 libivy.a $(DESTDIR)$(PREFIX)/lib/
	install -m644 libivy.dylib $(DESTDIR)$(PREFIX)/lib/

includes:
	test -d $(DESTDIR)$(PREFIX)/include/Ivy || mkdir -p $(DESTDIR)$(PREFIX)/include/Ivy
	install -m644 ivy.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 ivybind.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 ivybuffer.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 ivychannel.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 ivydebug.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 ivyloop.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 ivysocket.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 list.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 timer.h $(DESTDIR)$(PREFIX)/include/Ivy/
	install -m644 version.h $(DESTDIR)$(PREFIX)/include/Ivy/

installbins: tools
	test -d $(DESTDIR)$(PREFIX)/bin || mkdir -p $(DESTDIR)$(PREFIX)/bin
	install -m755 $(TOOLS_DIR)/ivyprobe $(DESTDIR)$(PREFIX)/bin
	install -m755 $(TOOLS_DIR)/ivyperf $(DESTDIR)$(PREFIX)/bin

tools: static-libs
	@(cd $(TOOLS_DIR) && $(MAKE) -f Makefile.osx)

install: installlibs installbins includes installpkgconf

clean:
	-rm -f *.o *.a *.dylib *.dylib.* *~ *.pc
	@(cd $(TOOLS_DIR) && $(MAKE) -f Makefile.osx clean)

pkgconf:
	for f in ivy-c.pc.in ; do \
		sed -e 's,/lib64,/lib,; s,@PREFIX@,$(PREFIX),; s,@MAJOR@,$(MAJOR),; s,@MINOR@,$(MINOR),; s,@PCRELIB@,$(PCRELIB),; s,@EXTRALIB@,$(EXTRALIB),' $$f > libivy.pc ; \
	done

installpkgconf: pkgconf
	test -d $(DESTDIR)$(PREFIX)/lib/pkgconfig || mkdir -p $(DESTDIR)$(PREFIX)/lib/pkgconfig
	install -m 644 *.pc $(DESTDIR)$(PREFIX)/lib/pkgconfig
